# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('D_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('D_Name', models.CharField(max_length=20)),
                ('C_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aadhaar', models.CharField(max_length=12)),
                ('F_Name', models.CharField(max_length=50)),
                ('F_Addr', models.TextField(max_length=150)),
                ('F_Ph_NO', models.CharField(max_length=15)),
                ('AC_NO', models.CharField(max_length=16)),
                ('Apply_Date', models.DateTimeField(auto_now_add=True)),
                ('VerifiedStatus', models.CharField(default='0', max_length=1)),
                ('ConfirmedStatus', models.CharField(default='0', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aadhaar', models.CharField(max_length=12)),
                ('Quanity', models.IntegerField()),
                ('Rate', models.IntegerField()),
                ('Amount', models.IntegerField()),
                ('Transaction_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('L_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('L_Name', models.CharField(max_length=20)),
                ('C_Date', models.DateTimeField(auto_now_add=True)),
                ('D_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.District')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_id', models.CharField(max_length=10)),
                ('Item_Name', models.CharField(max_length=50)),
                ('Buy_Price', models.IntegerField()),
                ('Sell_Price', models.IntegerField()),
                ('D_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.District')),
            ],
        ),
        migrations.AddField(
            model_name='farmertransaction',
            name='Item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Price'),
        ),
        migrations.AddField(
            model_name='farmerdetails',
            name='Item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Price'),
        ),
        migrations.AddField(
            model_name='farmerdetails',
            name='L_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Local'),
        ),
    ]
