# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_buyertransaction_l_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerdetails',
            name='AC_NO',
        ),
    ]
