# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_farmerdetails_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyertransaction',
            name='Amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='buyertransaction',
            name='Quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='buyertransaction',
            name='Rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='farmertransaction',
            name='Amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='farmertransaction',
            name='Quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='farmertransaction',
            name='Rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='routes',
            name='Quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Quantity',
            field=models.FloatField(),
        ),
    ]
