# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170303_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerdetails',
            name='AC_NO',
            field=models.CharField(default='XXXX', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerdetails',
            name='IFSC',
            field=models.CharField(default='DLXB', max_length=11),
            preserve_default=False,
        ),
    ]
