# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_farmerfiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmerfiles',
            old_name='Aadhaar_pic',
            new_name='Aadhaar_Pic',
        ),
    ]
