# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20170311_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerfiles',
            name='Aadhaar_Pic',
            field=models.FileField(upload_to='/media'),
        ),
        migrations.AlterField(
            model_name='farmerfiles',
            name='Field_Pic',
            field=models.FileField(upload_to='/media'),
        ),
    ]
