# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20170311_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerfiles',
            name='farmer',
        ),
        migrations.DeleteModel(
            name='FarmerFiles',
        ),
    ]
