# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc',
            field=models.FileField(default='null', upload_to='documents/'),
            preserve_default=False,
        ),
    ]
