# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_document_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerdetails',
            name='doc',
            field=models.FileField(default='na', upload_to=b''),
            preserve_default=False,
        ),
    ]
