# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_farmerdetails_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerdetails',
            name='AadhaarPic',
            field=models.FileField(default='Not added', upload_to=b''),
            preserve_default=False,
        ),
    ]
