# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_farmerdetails_aadhaarpic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
