# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_delete_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='Item_id',
            field=models.CharField(max_length=10),
        ),
    ]
