# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20170329_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='SendStatus',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
