# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_routes_sendstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='WaitForAllocation',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
